{% set name = "nikola" %}
{% set version = "8.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Nikola-{{ version }}.tar.gz
  sha256: 95f4ab051c2458c1d31442782a6ad6231f5720c3b923d5f172e25eef34f126c1

build:
  number: 0
  noarch: python
  entry_points:
    - nikola = nikola.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - babel >=2.6.0
    - blinker >=1.3
    - docutils >=0.13
    - doit >=0.32.0
    - lxml >=3.3.5
    - mako >=1.0.0
    - markdown >=3.0.0
    - natsort >=3.5.2
    - piexif >=1.0.3
    - pillow >=2.4.0
    - pygments >=1.6
    - pyrss2gen >=1.1
    - python >=3.5
    - python-dateutil >=2.6.0
    - requests >=2.2.0
    - setuptools >=24.2.0
    - unidecode >=0.04.16
    - yapsy >=1.11.223
  # https://github.com/getnikola/nikola/blob/master/requirements-extras.txt
  run_constrained:
    - jinja2 >=2.7.2
    - husl >=4.0.2
    - pyphen >=0.9.1
    - micawber >=0.3.0
    - pygal >=2.0.0
    - typogrify >=2.0.4
    - phpserialize >=1.3
    - notebook >=4.0.0
    - ipykernel >=4.0.0
    # see issue #2
    - ghp-import >=1.0.0
    - aiohttp >=3.0.0
    - watchdog >=0.8.3
    - ruamel.yaml >=0.15
    - toml >=0.9.2

test:
  imports:
    - nikola
    - nikola.packages
  commands:
    - pip check
    - nikola --help
  requires:
    - pip

about:
  home: https://getnikola.com/
  summary: A modular, fast, simple, static website and blog generator
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ickc
